name: Apply Patch From Comment
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # 宽松触发：支持 ```patch / ```diff / 纯文本 diff --git
    if: ${{ contains(github.event.comment.body, '```patch') || contains(github.event.comment.body, '```diff') || contains(github.event.comment.body, 'diff --git') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: false }

      - name: Debug (who/what)
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Action: ${{ github.event.action }}"
          echo "---- First lines of comment ----"
          echo "${{ github.event.comment.body }}" | head -n 10

      - name: Extract patch
        run: |
          python - <<'PY'
          import json, os, re
          ev = json.load(open(os.environ['GITHUB_EVENT_PATH']))
          body = ev["comment"]["body"]
          m = re.search(r"```(?:patch|diff)\s*(.*?)\s*```", body, re.S)
          if not m:
              m = re.search(r"(diff --git.*)", body, re.S)
          assert m, "No patch content found"
          open("chat.patch","w",encoding="utf-8").write(m.group(1))
          print("Wrote chat.patch")
          PY

      - name: Configure git auth
        run: |
          git config user.name "chat-bot"
          git config user.email "chat-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Apply & push PR branch
        run: |
          set -e
          BR="chatpatch-$(date +%s)"
          git checkout -b "$BR"
          git apply chat.patch
          git add -A
          git commit -m "Patch from chat"
          git push origin "$BR"
          echo "BRANCH=$BR" >> $GITHUB_ENV

      # （替换原来的 Open PR 步骤）
      - name: Open PR via API
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo
            const head = process.env.BRANCH
            const base = "main"
            const title = "Patch from chat"
            const body = "Auto-created from issue comment."
            const res = await github.pulls.create({
              owner, repo, head, base, title, body,
              maintainer_can_modify: true, draft: false
            })
            core.info(`PR #${res.data.number} -> ${res.data.html_url}`)

