name: Apply Patch From Comment
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
jobs:
  apply:
    if: contains(github.event.comment.body, '```patch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Extract patch
        run: |
          python - <<'PY'
          import json,os,re
          ev=json.load(open(os.environ['GITHUB_EVENT_PATH']))
          m=re.search(r"```patch\s*(.*?)\s*```", ev["comment"]["body"], re.S)
          assert m, "No ```patch block found"
          open("chat.patch","w",encoding="utf-8").write(m.group(1))
          PY
      - name: Apply & push PR branch
        run: |
          set -e
          BR="chatpatch-$(date +%s)"
          git config user.name "chat-bot"
          git config user.email "chat-bot@users.noreply.github.com"
          git checkout -b "$BR"
          git apply chat.patch
          git add -A
          git commit -m "Patch from chat"
          git push origin "$BR"
          echo "BRANCH=$BR" >> $GITHUB_ENV
      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Patch from chat"
          body: "Auto-created from issue comment."
          branch: ${{ env.BRANCH }}
          base: main
