name: Apply Patch From Comment

on:
  issue_comment:
    types: [created]
  # 可选：手动触发（用于测试）
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # 更宽松的触发条件：三种写法都能触发
    if: ${{ contains(github.event.comment.body, '```patch') || contains(github.event.comment.body, '```diff') || contains(github.event.comment.body, 'diff --git') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: false }

      - name: Debug (who/what)
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Action: ${{ github.event.action }}"
          echo "Starts with:"
          echo "${{ github.event.comment.body }}" | head -n 5

      - name: Extract patch
        run: |
          python - <<'PY'
          import json, os, re, sys
          ev = json.load(open(os.environ['GITHUB_EVENT_PATH']))
          body = ev["comment"]["body"]
          # 先找 ```patch/```diff 代码块
          m = re.search(r"```(?:patch|diff)\s*(.*?)\s*```", body, re.S)
          # 找不到就退化为从 diff --git 开始的全部
          if not m:
              m = re.search(r"(diff --git.*)", body, re.S)
          assert m, "No patch content found"
          open("chat.patch","w",encoding="utf-8").write(m.group(1))
          print("Wrote chat.patch with", len(m.group(1)), "bytes")
          PY

      - name: Configure git auth
        run: |
          git config user.name "chat-bot"
          git config user.email "chat-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Apply & push PR branch
        run: |
          set -e
          BR="chatpatch-$(date +%s)"
          git checkout -b "$BR"
          git apply chat.patch
          git add -A
          git commit -m "Patch from chat"
          git push origin "$BR"
          echo "BRANCH=$BR" >> $GITHUB_ENV

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Patch from chat"
          body: "Auto-created from issue comment."
          branch: ${{ env.BRANCH }}
          base: main
