name: Cleanup merged PR

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch on merge
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const branch = context.payload.pull_request.head.ref;
            core.info(`Deleting merged branch: ${branch}`);
            await github.rest.git.deleteRef({
              owner, repo,
              ref: `heads/${branch}`
            });
